### PR TITLE
fix(horizon-householder-appeal-publish): update mapping value

### PR DESCRIPTION
**Pull request by frank-dodion**
## Ticket Number
AS-1462

## Description of change
Update Source Indicator mapping value

### CODE REVIEW

**Review by MrSimonEmms — COMMENTED** [review]
Has this been tested against a real Horizon to check it works?

**Comment by frank-dodion** [comment]
> Has this been tested against a real Horizon to check it works?

No. I understand that an admin is required to revert the state after manual testing. Shall we arrange this?

**Comment by MrSimonEmms** [comment]
> > Has this been tested against a real Horizon to check it works?
> 
> No. I understand that an admin is required to revert the state after manual testing. Shall we arrange this?

I am the admin. Just let me know when you've finished and I'll do it

**Comment by frank-dodion** [comment]
> > > Has this been tested against a real Horizon to check it works?
> > 
> > 
> > No. I understand that an admin is required to revert the state after manual testing. Shall we arrange this?
> 
> I am the admin. Just let me know when you've finished and I'll do it

I think the changes for this ticket are done.

**Review by danWatkinson — APPROVED** [review]
lgtm

**Pull request merged**
