### PR TITLE
feat(forms-web-app): display alternative content for /cookies when JS is disabled

### PR DESCRIPTION
**Pull request by a6software**
## Ticket Number

AS-1351

## Description of change
display alternative content for /cookies when JS is disabled

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [x] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Comment by swdpcomputing** [comment]
When I navigate to: https://www.gov.uk/guidance/appeals-casework-portal-privacy-cookies with js turned off it still appears. Only when I go to here: https://www.gov.uk/help/cookies do I see the screen as posted in the ticket (screenshot attached). I get there from the cookies info dropdown at the top of the page. Is this expected behaviour?

Screenshot 2021-03-19 at 08 59 01

**Review by Fenisay — APPROVED** [review]
LGTM

**Comment by a6software** [comment]
Hi @swdpcomputing - thanks for the in-depth review.

As discussed on chat, I have done the following:

1. Updated the retro items to discuss putting enough context on the tickets so any team member can QA effectively. Sorry about this! 
2. Updated the ticket (https://pins-ds.atlassian.net/browse/AS-1351) with longer test notes.

Here's what I found whilst working through your steps:

1. The cookies link in the footer is misleading, but not incorrect (as per business requirements). 
 
2. _"https://www.gov.uk/guidance/appeals-casework-portal-privacy-cookies with js turned of the previous, js enabled page still appears."_ -> very much misleading as a result of the issue you raised in #1 - this work only impacts `/cookies` page on our site, though our site closely (but not exactly) mirrors the content on the gov uk link.
 
3. _"Only when I go to here: https://www.gov.uk/help/cookies do I see the screen as posted in the ticket (screenshot attached)."_ -> yes, again, confusing as per #2. The AS-1351 ticket only includes a screenshot of the requested content. I have pretty much done a copy / paste from the gov uk cookies page. 
 
The difference between the two pages is that ours does not / should not have the block "Government services" or the block "help us improve gov uk".

Here's what I see:

no-js
 
4. _"I get there from the cookies info dropdown at the top of the page. Is this expected behaviour?"_ -> no, though I suspect this is from following the cookies info link in the banner on the gov uk site (due to the misleading behaviour in #1) rather than seeing the intended content on our site.

Hopefully this addresses all the concerns. Thanks for the review / your time in giving a video explanation, and sorry for the confusion caused!

**Review by swdpcomputing — CHANGES_REQUESTED** [review]
Issues with correct / clear routing.
Issue with different page appearing whether cookies have been accepted.

Commented by C Moss in ticket: https://pins-ds.atlassian.net/browse/AS-1351?atlOrigin=eyJpIjoiY2QzYzc0ZWM0ZmRjNDg4YTg1Yjk3NDQ0MTliMjliODIiLCJwIjoiaiJ9

**Comment by a6software** [comment]
> Issues with correct / clear routing.
> Issue with different page appearing whether cookies have been accepted.
> 
> Commented by C Moss in ticket: https://pins-ds.atlassian.net/browse/AS-1351?atlOrigin=eyJpIjoiY2QzYzc0ZWM0ZmRjNDg4YTg1Yjk3NDQ0MTliMjliODIiLCJwIjoiaiJ9

I believe all changes requested have now been addressed. 

Ticket test notes added.

**Review by Fenisay — APPROVED** [review]
LGTM

**Comment by a6software** [comment]
Heads up, going to merge this after 2pm today unless i hear feedback to say otherwise

**Comment by a6software** [comment]
Hi @swdpcomputing - any chance of a review on this as I can't progress further with this without your approval. Thanks

**Review by swdpcomputing — APPROVED** [review]

**Comment by a6software** [comment]
ty

**Pull request merged**
