### PR TITLE
test: updated failing cypress tests for lpa-questionnaire

### PR DESCRIPTION
**Pull request by demzzydev**
fix(as-3319): fix for failing test when returning from supplementary docs page to tasklist in lpaq

fix(as-3380): remove mock id from url

fix(as-3360): fix supplementary uploaded document

fix(as-3360): fix supplementary document delete

## Ticket Number
AS-3380
https://pins-ds.atlassian.net/browse/AS-3380

## Description of change
Fixed minor issues with routing

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Comment by shepda** [comment]
Not sure we need this as these look like the changes I did to get the unit tests working in the pipeline and these should already be on this branch?

Also don't think we need to add `bugfix` to the triggers as this is the same as `fix` which is already there?

**Comment by demzzydev** [comment]
> Not sure we need this as these look like the changes I did to get the unit tests working in the pipeline and these should already be on this branch?
> 
> Also don't think we need to add `bugfix` to the triggers as this is the same as `fix` which is already there?

We don't but in order to get over the issue that Shilpa was talking about I had to add an additional flag so that the builds can pass.

**Comment by shepda** [comment]
How does this help the issue, are there specific branches failing because of the prefix? I'd just like to understand a bit more about the reason for adding it.

**Comment by demzzydev** [comment]
> How does this help the issue, are there specific branches failing because of the prefix? I'd just like to understand a bit more about the reason for adding it.

This helps because the check looks for the prefix on the commits and PRs, so even though we change the branch name because we've made commits on a branch with the wrong prefix, the check still fails.

**Pull request closed without merging**
