### PR TITLE
feat(magic-link): adds authentication-service-api and redis

### PR DESCRIPTION
**Pull request by Russ-Clarke**
## Ticket Number

https://pins-ds.atlassian.net/browse/AS-2863

## Description of change
Creates Redis resource
Creates authentication-service-api
Alters docker-compose for local dev

## Checklist

- [x] Requires infrastructure changes
- [x] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Comment by LouiseMcMahon** [comment]
I think ive found whats failing your builds https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/1440 should fix it but basically the new Node images have NPM 7 which isnt compatible with NPM 6. No your fault just bad timing.

**Comment by LouiseMcMahon** [comment]
Thats merged now if you want to rebase your branch and see if that helps

**Comment by Russ-Clarke** [comment]
Thanks @LouiseMcMahon but the tests still seemed to fail. Appreciate the help.

**Review by LouiseMcMahon — APPROVED** [review]
Brilliant the local dev side looks good to me though someone with more TF experience than me should look at that

**Review by rajeshwar2kc — APPROVED** [review]

**Review by AnthonyJWalsh — APPROVED** [review]
I know literally nothing about Terraform or any of this, so relying on the expertise of Louise and Raj. Clicking approve so we can progress.

**Pull request merged**
