### PR TITLE
fix(as-2538): ensure NPM and Node version is within the expected range

### PR DESCRIPTION
**Pull request by a6software**
## Ticket Number

https://pins-ds.atlassian.net/browse/AS-2538

## Description of change
ensure NPM and Node version is within the expected range

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Review by swdpcomputing — DISMISSED** [review]
LGTM

**Review by rcmsoftwaredevelopment — APPROVED** [review]

**Comment by a6software** [comment]
Note to self: nvmrc

**Review by davehlewis — APPROVED** [review]
LGTM

**Comment by a6software** [comment]
cheers all!

**Pull request merged**
