### PR TITLE
fix(horizon-householder-appeal-publish): update mapping

### PR DESCRIPTION
**Pull request by frank-dodion**
## Ticket Number
AS-1342

## Description of change
Update mapping

### CODE REVIEW

**Comment by MrSimonEmms** [comment]
Looks fine. Has this been tested against a real Horizon call that it works as expected?

**Comment by frank-dodion** [comment]
> Looks fine. Has this been tested against a real Horizon call that it works as expected?

No. I am not sure how to do that before merging and deploying to dev.

**Review by rcmsoftwaredevelopment — APPROVED** [review]

**Comment by MrSimonEmms** [comment]
You're in luck. This is now enabled in `dev`. I went through it yesterday with @Fenisay and we documented it [here](https://github.com/Planning-Inspectorate/appeal-planning-decision#using-openfaas). I suspect you might want walking through it, so can help you with that if he's busy with the merge conflict

**Comment by frank-dodion** [comment]
> You're in luck. This is now enabled in `dev`. I went through it yesterday with @Fenisay and we documented it [here](https://github.com/Planning-Inspectorate/appeal-planning-decision#using-openfaas). I suspect you might want walking through it, so can help you with that if he's busy with the merge conflict

Thanks.

**Pull request merged**
