### PR TITLE
fix(as-4325): add formatting for the appeal deadline

### PR DESCRIPTION
**Pull request by demzzydev**
## Ticket Number

https://pins-ds.atlassian.net/browse/AS-4325

## Description of change
Add formatting for the appeal deadline

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Review by swdpcomputing — DISMISSED** [review]

**Review by nssdesikan — COMMENTED** [review]
LGTM from Dev perspective. 

Doesn't require any updates to E2E test to confirm the date format?

**Comment by demzzydev** [comment]
> LGTM from Dev perspective.
> 
> Doesn't require any updates to E2E test to confirm the date format?

There was an issue with the E2E test but haven't done any work to confirm the format as of yet. Will confirm with Shilpa on Monday.

**Comment by nssdesikan** [comment]
> > LGTM from Dev perspective.
> > Doesn't require any updates to E2E test to confirm the date format?
> 
> There was an issue with the E2E test but haven't done any work to confirm the format as of yet. Will confirm with Shilpa on Monday.

@demzzydev Did you get a chance to check with @shilpabasu22?

**Comment by demzzydev** [comment]
> > > LGTM from Dev perspective.
> > > Doesn't require any updates to E2E test to confirm the date format?
> > 
> > 
> > There was an issue with the E2E test but haven't done any work to confirm the format as of yet. Will confirm with Shilpa on Monday.
> 
> @demzzydev Did you get a chance to check with @shilpabasu22?

Spoke to her on Friday

**Review by swdpcomputing — APPROVED** [review]

**Review by shilpabasu22 — APPROVED** [review]
LGTM

**Comment by demzzydev** [comment]
Closing because branch is messed up

**Pull request closed without merging**
