### PR TITLE
refactor(update error messages in the appeal submission journey): update error messages

### PR DESCRIPTION
**Pull request by biroldif**
## Ticket Number
https://pins-ds.atlassian.net/browse/AS-2981

## Description of change
update error messages in the appeal submission journey

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Review by karunak21 — COMMENTED** [review]
all looks good

**Review by shepda — APPROVED** [review]
LGTM

**Review by shepda — APPROVED** [review]
LGTM

**Review by karunak21 — APPROVED** [review]
All looks good

**Pull request merged**
